[package]
name = "axon_parseast_parser"
version = "0.1.0"
authors = ["A Mackay <opensauceburner@outlook.com>"]
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19.1", features = ["lexer"] }

[dependencies]
chrono = "0.4"
lalrpop-util = "0.19.1"
raystack = "0.6"
regex = "1"